# main.tf — the entire thesis cluster, declaratively.
#
# Lifecycle (the standardization you asked for):
#   terraform apply   -> everything exists, identically, every time
#   terraform destroy -> everything gone, billing stops
#   terraform apply   -> identical rebuild from zero
#
# One file, three campaign phases via variables (see docs/CAMPAIGN_RUNBOOK.md):
#   Phase A  CFT baseline/faults : defaults                 3x ccx13 nodes
#   Phase B  Raft scalability D8 : -var consensus_node_count=7
#   Phase C  BFT upsized D9      : -var consensus_node_count=4 \
#                                  -var consensus_node_type=ccx23
#
# The dual-IP inventory (v6's fatal flaw C1) is GENERATED by this file on
# every apply — it cannot drift from reality because it is derived from it.
#
# Prereqs on the laptop: terraform >= 1.6, an hcloud API token
# (export TF_VAR_hcloud_token=...), and an SSH keypair.
# Local acceptance, no billing: terraform init && terraform validate
#   && terraform plan -var hcloud_token=dummy-local-check

terraform {
  required_version = ">= 1.6"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.45"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

variable "hcloud_token" {
  type      = string
  sensitive = true
}

variable "ssh_public_key_path" {
  type    = string
  default = "~/.ssh/hetzner_thesis.pub"
}

variable "location" {
  type    = string
  default = "fsn1" # fallback if CCX13 out of stock: nbg1, hel1
}

variable "consensus_node_count" {
  type    = number
  default = 3 # CFT quorum default; 4 for the BFT phase, 7 for D8 scalability
  validation {
    condition     = var.consensus_node_count >= 1 && var.consensus_node_count <= 7
    error_message = "consensus_node_count must be 1..7 (D8 ceiling; IPs 10.0.0.11-17)."
  }
}

variable "consensus_node_type" {
  type    = string
  default = "ccx13" # 2 dedicated vCPU (Paxi/Charapko class); ccx23|ccx33 for BFT (D9)
}

variable "loadgen_type" {
  type    = string
  default = "ccx13" # D11: the measuring instrument gets dedicated vCPUs too
}

variable "obs_type" {
  type    = string
  default = "cpx21" # shared vCPU acceptable: Prometheus/Grafana are not measured
}

provider "hcloud" {
  token = var.hcloud_token
}

# ---------------------------------------------------------------------------
# Topology: N dedicated-vCPU consensus nodes + dedicated loadgen + shared obs.
# Static private IPs so the inventory is deterministic across rebuilds.
# ---------------------------------------------------------------------------
locals {
  consensus_nodes = {
    for i in range(var.consensus_node_count) :
    "node${i + 1}" => { type = var.consensus_node_type, ip = "10.0.0.${11 + i}" }
  }
  support = {
    loadgen = { type = var.loadgen_type, ip = "10.0.0.20" }
    obs     = { type = var.obs_type, ip = "10.0.0.21" }
  }
  vms = merge(local.consensus_nodes, local.support)

  # Hourly prices, EUR, post-2026-06 Hetzner repricing (gathered 2026-07-07).
  # The apply-time truth is `hcloud server-type list`; a type missing from
  # this map counts as 0 in the estimate — keep it in sync when adding types.
  hourly_eur = {
    ccx13 = 0.0689
    ccx23 = 0.1378
    ccx33 = 0.1923
    cpx21 = 0.016 # unconfirmed post-repricing — verify before relying on it
  }
}

resource "hcloud_ssh_key" "thesis" {
  name       = "thesis-key"
  public_key = file(pathexpand(var.ssh_public_key_path))
}

resource "hcloud_network" "thesis" {
  name     = "thesis-net"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "thesis" {
  network_id   = hcloud_network.thesis.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.0.0/24"
}

# Spread placement: each VM on a distinct physical host, so inter-node
# latency does not depend on which hypervisor a rebuild happened to land on
# (reproducibility threat otherwise invisible to every validity check).
# Hetzner caps a spread group at 10 servers; our maximum is 9 (7+2).
resource "hcloud_placement_group" "spread" {
  name = "thesis-spread"
  type = "spread"
}

# Public interface: SSH only. Consensus traffic rides the private network;
# Grafana/Prometheus are reached through an SSH tunnel, never exposed.
resource "hcloud_firewall" "ssh_only" {
  name = "thesis-ssh-only"
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "22"
    source_ips = ["0.0.0.0/0", "::/0"]
  }
  rule {
    direction  = "in"
    protocol   = "icmp"
    source_ips = ["0.0.0.0/0", "::/0"]
  }
}

resource "hcloud_server" "vm" {
  for_each           = local.vms
  name               = "thesis-${each.key}"
  server_type        = each.value.type
  image              = "ubuntu-24.04"
  location           = var.location
  ssh_keys           = [hcloud_ssh_key.thesis.id]
  firewall_ids       = [hcloud_firewall.ssh_only.id]
  placement_group_id = hcloud_placement_group.spread.id
  user_data          = file("${path.module}/cloud-init.yaml")

  network {
    network_id = hcloud_network.thesis.id
    ip         = each.value.ip
  }

  depends_on = [hcloud_network_subnet.thesis]
}

# ---------------------------------------------------------------------------
# The inventory is an OUTPUT of the infrastructure, written on every apply.
# Public IPs for laptop->VM admin; private IPs for everything inter-node.
# ---------------------------------------------------------------------------
resource "local_file" "inventory" {
  filename        = "${path.module}/../deploy/inventory.env"
  file_permission = "0644"
  content = <<-EOT
    # GENERATED by terraform apply — do not edit by hand.
    # Public IPs: laptop -> VM (SSH admin). Private IPs: inter-node only.
    ${join("\n", [for k, v in hcloud_server.vm :
  "PUBLIC_${upper(k)}=${v.ipv4_address}"])}

    ${join("\n", [for k, v in local.vms :
"PRIVATE_${upper(k)}=${v.ip}"])}

    CONSENSUS_NODE_COUNT=${var.consensus_node_count}
    CONSENSUS_NODE_TYPE=${var.consensus_node_type}
    SSH_KEY=${replace(var.ssh_public_key_path, ".pub", "")}
    LOCATION=${var.location}
  EOT
}

output "ssh_loadgen" {
  value = "ssh -i ${replace(var.ssh_public_key_path, ".pub", "")} root@${hcloud_server.vm["loadgen"].ipv4_address}"
}

output "hourly_cost_estimate_eur" {
  value = format("≈ €%.3f/hour while up (%d VMs, prices as of 2026-06 repricing); €0 after destroy",
    sum([for v in local.vms : lookup(local.hourly_eur, v.type, 0)]),
  length(local.vms))
}
